---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "drukkhua"
          password: "dckr_pat__POLLzxIVb_wYwllt006fX46Aj0"
#          username: "${{ secrets.DOCKERHUB_USER }}"
#          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
#run: echo "KEY=VALUE" >>$GITHUB_OUTPUT
#steps:
#  - name: Set the value
#    id: step_one
#    run: |
#      echo "action_state=yellow" >> $GITHUB_ENV
#  - name: Use the value
#    id: step_two
#    run: |
#      echo "${{ env.action_state }}" # This will output 'yellow'